### ISSUE TITLE
[How To] demo app

### ISSUE THREAD

**Issue by kirantpatil** [blackxored/jquery-svg-rails#1]
Hi,

Can you post a demo app for this gem ?

Thanks.

**Comment by blackxored** [comment]
Hi,
This only encapsulates the original JS library for easier usage within Rails, sadly the app where I needed it it's private (we used it for SVG color animation), but with the usage section in the README and the examples here: http://keith-wood.name/svg.html#examples, I think you could do well. Let me know if it helps.

**Comment by kirantpatil** [comment]
Here is my svg file where I need to change the colour of the id slot1, slot2, ... Can you just put some code to do it ?

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:osb="http://www.openswatchbook.org/uri/2009/osb"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   version="1.1"
   id="svg80602"
   viewBox="0 0 744.09448819 1052.3622047"
   height="297mm"
   width="210mm">
  <defs
     id="defs80604">
    <linearGradient
       osb:paint="solid"
       id="linearGradient81412">
      <stop
         id="stop81414"
         offset="0"
         style="stop-color:#0000ff;stop-opacity:1;" />
    </linearGradient>
  </defs>
  <metadata
     id="metadata80607">
    rdf:RDF
      <cc:Work
         rdf:about="">
        dc:formatimage/svg+xml/dc:format
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        dc:title/dc:title
      /cc:Work
    /rdf:RDF
  </metadata>
  <g
     id="layer1">
    <rect
       y="109.88521"
       x="164.82782"
       height="71.848022"
       width="25.358126"
       id="slot1"
       style="fill:#008000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
    <rect
       style="fill:none;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       id="slot2"
       width="25.358126"
       height="71.848022"
       x="190.82782"
       y="109.88521" />
    <rect
       y="109.88521"
       x="218.82782"
       height="71.848022"
       width="25.358126"
       id="slot3"
       style="fill:#ffff00;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
    <rect
       style="fill:none;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       id="slot4"
       width="25.358126"
       height="71.848022"
       x="242.82782"
       y="109.88521" />
  </g>
</svg>

**Comment by kirantpatil** [comment]
closing this as i got it worked ..
